### ISSUE TITLE
Can't find freexl library

### ISSUE THREAD

**Issue by vioannid** [spebern/Parser-FreeXL-Native#2]
Hello,

I installed the module using  
`zef install Parser::FreeXL::Native`

I noticed the following warning  
`configure: WARNING: 'missing' script is too old or missing`

but it seems the module was installed anyway  

`
zef search Parser::FreeXL ===> Found 2 results
-----------------------------------------------------------------------------------------------------------
ID|From                            |Package                          |Description                          
-----------------------------------------------------------------------------------------------------------
0 |Zef::Repository::LocalCache     |Parser::FreeXL::Native:ver<0.0.2>|wrapper for freexl parsing .xls files
1 |Zef::Repository::Ecosystems<p6c>|Parser::FreeXL::Native:ver<0.0.2>|wrapper for freexl parsing .xls files
-----------------------------------------------------------------------------------------------------------
`

However, when I run a script based on your demo, I get the following error message in return:  
`Cannot locate native library './lib/libfreexl.dylib': dlopen(./lib/libfreexl.dylib`

Thank you for your help,
vassilios

**Comment by wenjie1991** [comment]
Hi, vassilios,
If you are still need to read .xls file using Raku (Perl 6). You can try it again. I hope the problem has been solved by the [last commit](https://github.com/spebern/Parser-FreeXL-Native/commit/e97a6570c9f6ddffa287d6583c05960dbc47deb3).

P.S. You need to install the FreeXL lib first:
```
# In macos
brew install freexl 
# In ubuntu (I guess)
sudo apt-get install libfreexl-dev libfreexl1
```

**Comment by vioannid** [comment]
Hello,

Thank you for your message.

Please note that there is still an error upon installation:
```
===> Testing [FAIL]: Parser::FreeXL::Native:ver<0.0.3>
Aborting due to test failure: Parser::FreeXL::Native:ver<0.0.3> (use --force-test to override)
```

**Comment by wenjie1991** [comment]
Hi,
I have tested the package in MacOS and [ubuntu](https://travis-ci.com/wenjie1991/Parser-FreeXL-Native/jobs/268683832). To be honest, the error message you provided is not sufficient for me to help you debug. Could you tell me the OS you are using as well as the Raku (Perl 6) version?
